export const TRANSACTION_AMOUNT_CHANGE = 'zilean/Transactions/TRANSACTION_AMOUNT_CHANGE';
export const HYPOTHETICAL_TRANSACTION_RESULT = 'zilean/Transactions/HYPOTHETICAL_TRANSACTION_RESULT';
export const EXECUTE_TRANSACTION = 'zilean/Transactions/EXECUTE_TRANSACTION';
export const EXECUTE_TRANSACTION_SUCCESS = 'zilean/Transactions/EXECUTE_TRANSACTION_SUCCESS';
export const EXECUTE_TRANSACTION_ERROR = 'zilean/Transactions/EXECUTE_TRANSACTION_ERROR';
