export const TRANSACTION_AMOUNT_CHANGE = 'zilean/Transactions/TRANSACTION_AMOUNT_CHANGE';
export const EXECUTE_HYPOTHETICAL_TRANSACTION = 'zilean/Transactions/EXECUTE_HYPOTHETICAL_TRANSACTION';
export const HYPOTHETICAL_TRANSACTION_SUCCESS = 'zilean/Transactions/HYPOTHETICAL_TRANSACTION_SUCCESS';
export const HYPOTHETICAL_TRANSACTION_ERROR = 'zilean/Transactions/HYPOTHETICAL_TRANSACTION_ERROR';
export const EXECUTE_TRANSACTION = 'zilean/Transactions/EXECUTE_TRANSACTION';
export const EXECUTE_TRANSACTION_SUCCESS = 'zilean/Transactions/EXECUTE_TRANSACTION_SUCCESS';
export const EXECUTE_TRANSACTION_ERROR = 'zilean/Transactions/EXECUTE_TRANSACTION_ERROR';
