branch-defaults:
  master:
    environment: zilean-prod
    group_suffix: null
environment-defaults:
  zilean3-dev:
    branch: null
    repository: null
global:
  application_name: zilean2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git
